Add nginx reloading when new ssl released
Moneyfactory-io/blockscout-frontend pull request #56
Opened 2024-09-03 12:17 UTC by semeniak97mf

Added reloading of the nginx automatically if a new ssl from certbot had been released.

Actions: https://github.com/Atleta-network/blockscout/actions/runs/10682406773

2024-09-03 13:32 UTC, hrls requested changes

2024-09-03 13:32 UTC, hrls commented on .github/workflows/deploy.yml
> +          docker build --build-arg GIT_COMMIT_SHA=$(git rev-parse --short HEAD) --build-arg GIT_TAG=$(git describe --tags --abbrev=0) -t nginx-explorer nginx-docker/
Remove unused build args.

2024-09-03 13:32 UTC, hrls commented on .github/workflows/deploy.yml
> +          docker build --build-arg GIT_COMMIT_SHA=$(git rev-parse --short HEAD) --build-arg GIT_TAG=$(git describe --tags --abbrev=0) -t nginx-explorer nginx-docker/
Move `nginx-docker/` into `docker/nginx/` subdir.

2024-09-03 13:32 UTC, hrls commented on nginx-docker/docker-entrypoint.sh
`command: /check_ssl.sh & ./entrypoint.sh "nginx -g 'daemon off;'"` or something like this, then we can remove thirdparty entrypoint script.

2024-09-03 13:47 UTC, ales-tsurko commented on deploy/services/certbot.yml
> +    restart: unless-stopped
Make sure it should be restarted. Probably its purpose is running once to just generate certificates. I don’t remember though.

2024-09-03 17:10 UTC, semeniak97mf commented on .github/workflows/deploy.yml
> +          docker build --build-arg GIT_COMMIT_SHA=$(git rev-parse --short HEAD) --build-arg GIT_TAG=$(git describe --tags --abbrev=0) -t nginx-explorer nginx-docker/
Done

2024-09-03 17:13 UTC, semeniak97mf commented on nginx-docker/docker-entrypoint.sh
Moved it to Dockerfile. 
This is a working and more optimal way, thank you

2024-09-03 17:15 UTC, semeniak97mf commented on deploy/services/certbot.yml
> +    restart: unless-stopped
Just in case, I changed this option to `always`. Thanks

2024-09-04 08:44 UTC, hrls commented on .github/workflows/deploy.yml
> +            docker compose up --detach --build --remove-orphans
This `--build` flag is still required?

2024-09-04 08:44 UTC, hrls approved these changes

2024-09-11 08:29 UTC, ales-tsurko approved these changes

2024-09-11 08:46 UTC, merged